version: '2'
services:
  db:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=concentratio
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - db_data:/var/lib/mysql # db_dataフォルダの名前を変更している場合は、変更後のフォルダ名で書き換える
      - ./db_data:/docker-entrypoint-initdb.d # db_dataフォルダの名前を変更している場合は、変更後のフォルダ名で書き換える
      - ./db_data:/etc/mysql/conf.d # db_dataフォルダの名前を変更している場合は、変更後のフォルダ名で書き換える
    ports:
      - '3333:3306'

volumes:
  db_data:
    driver: local
